const Tabs = ["Summary", "Notes", "Quiz"];
const transcript_api = import.meta.env.VITE_TRNSCIPT_API
const claude_api = import.meta.env.VITE_CLAUDE_API 
const extractVideoId = (url) => {
  const patterns = [
    /(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/)([^&\n?#]+)/,
    /^([a-zA-Z0-9_-]{11})$/,
  ];
  for (const p of patterns) {
    const m = url.match(p);
    if (m) return m[1];
  }
  return null;
};

const fetchTranscript = async (videoId) => {
  const res = await fetch(`${transcript_api}${videoId}`);
  const data = await res.json();
  if (data.error) throw new Error(data.error);
  return data.transcript;
};

const callClaude = async (prompt) => {
  const res = await fetch(claude_api, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ prompt }),
  });
  const data = await res.json();
  if (data.error) throw new Error(data.error);
  return data.text || "";
};

const parseQuiz = (raw) => {
  if (!raw) return null;

  let clean = raw
    .replace(/```json/gi, "")
    .replace(/```/g, "")
    .trim();

  // Attempt 1: direct parse
  try { return JSON.parse(clean); } catch (e){
    console.error("Quiz parse error:", e);
  }

  // Attempt 2: extract [...] block
  try {
    const match = clean.match(/\[[\s\S]*\]/);
    if (match) return JSON.parse(match[0]);
  } catch (e){
    console.error("Quiz parse error:", e);
  }

  // Attempt 3: slice from first [ to last ]
  try {
    const start = clean.indexOf("[");
    const end = clean.lastIndexOf("]");
    if (start !== -1 && end !== -1 && end > start)
      return JSON.parse(clean.slice(start, end + 1));
  } catch(e) {
    console.error("Quiz parse error:", e);
  }

  // Attempt 4: fix trailing commas then parse
  try {
    const sliced = clean.slice(clean.indexOf("["), clean.lastIndexOf("]") + 1);
    const fixed = sliced.replace(/,\s*([}\]])/g, "$1");
    return JSON.parse(fixed);
  } catch (e){
    console.error("Quiz parse error:", e);
  }

  return null;
};

const downloadTxt = (content, filename) => {
  const plain = content
    .replace(/<h2>(.*?)<\/h2>/g, "\n\n== $1 ==\n")
    .replace(/<h3>(.*?)<\/h3>/g, "\n-- $1 --\n")
    .replace(/<strong>(.*?)<\/strong>/g, "$1")
    .replace(/<li[^>]*>(.*?)<\/li>/g, "  - $1\n")
    .replace(/<ul>(.*?)<\/ul>/gs, "$1")
    .replace(/<br\/?>/g, "\n")
    .replace(/<[^>]+>/g, "")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
  const blob = new Blob([plain], { type: "text/plain" });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = filename;
  a.click();
  URL.revokeObjectURL(a.href);
};

const downloadHtml = (content, filename, title) => {
  const dateStr = new Date().toLocaleDateString();
  const html = [
    "<!DOCTYPE html><html lang='en'><head><meta charset='UTF-8'/>",
    "<meta name='viewport' content='width=device-width,initial-scale=1'/>",
    "<title>" + title + "</title>",
    "<style>",
    "body{font-family:'Segoe UI',sans-serif;max-width:800px;margin:40px auto;padding:0 24px;color:#1a1a2e;line-height:1.8;}",
    "h1{color:#7c3aed;border-bottom:3px solid #7c3aed;padding-bottom:10px;}",
    "h2{color:#5b21b6;margin-top:32px;border-left:4px solid #7c3aed;padding-left:12px;}",
    "h3{color:#6d28d9;}",
    "strong{background:#ede9fe;padding:1px 5px;border-radius:3px;color:#4c1d95;}",
    "ul{padding-left:20px;}li{margin-bottom:6px;}",
    ".meta{color:#888;font-size:13px;margin-bottom:32px;}",
    "</style></head><body>",
    "<h1>" + title + "</h1>",
    "<p class='meta'>Generated by VidMind AI - " + dateStr + "</p>",
    content,
    "</body></html>"
  ].join("");
  const blob = new Blob([html], { type: "text/html" });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = filename;
  a.click();
  URL.revokeObjectURL(a.href);
};

const downloadQuiz = (quiz, score, submitted) => {
  let content = "<h1>Quiz Results</h1>";
  if (submitted) {
    const pct = Math.round((score / quiz.length) * 100);
    content += "<p class='meta'>Score: " + score + "/" + quiz.length + " (" + pct + "%)</p>";
  }
  quiz.forEach((q, i) => {
    content += "<h2>Q" + (i + 1) + ". " + q.q + "</h2><ul>";
    q.options.forEach((opt, ai) => {
      const correct = ai === q.answer;
      const style = correct ? "color:#16a34a;font-weight:700;" : "";
      content += "<li style='" + style + "'>" + ["A","B","C","D"][ai] + ". " + opt + (correct ? " ✓" : "") + "</li>";
    });
    content += "</ul>";
    if (q.explanation) {
      content += "<p style='background:#f3f0ff;padding:10px;border-radius:6px;font-size:14px;'>💡 " + q.explanation + "</p>";
    }
  });
  downloadHtml(content, "quiz.html", "VidMind Quiz");
};

const SUMMARY_PROMPT = (tx) => `You are an expert educational content creator. Analyze this YouTube video transcript and create a comprehensive, detailed summary in English only.

Your summary must include:
1. **Introduction** - What the video is about, who it is for, and why it matters (2-3 sentences)
2. **Main Topics Covered** - List and explain each major topic discussed in the video with enough detail that someone who has not watched it can fully understand
3. **Key Concepts and Definitions** - Explain any important terms, concepts, or ideas introduced
4. **Important Facts and Data** - Any statistics, dates, names, or factual information mentioned
5. **Conclusion and Takeaways** - What the viewer is expected to learn or do after watching

Write at least 400-500 words. Use clear paragraphs. Always reply in English only.

Transcript:
${tx.slice(0, 6000)}`;

const NOTES_PROMPT = (tx) => `You are an expert study notes creator. Create comprehensive, university-level study notes from this YouTube video transcript in English only.

Structure your notes as follows:

## Overview
Brief description of the topic and its importance.

## Learning Objectives
What you will learn from this video (bullet points).

## Detailed Notes
Break the content into clear sections with ## headings for each major topic. Under each section:
- Explain concepts thoroughly in your own words
- Use sub-bullets for supporting details
- **Bold** all key terms and important phrases
- Include examples where relevant
- Add any formulas, processes, or steps if mentioned

## Key Terms and Definitions
A glossary of all important terms mentioned with clear definitions.

## Important Points to Remember
The most critical facts, rules, or concepts from the video.

## Possible Exam Questions
5 short-answer questions a teacher might ask about this content.

## Summary
A 3-4 sentence recap of everything covered.

Write detailed, thorough notes of at least 600-800 words. Always reply in English only.

Transcript:
${tx.slice(0, 6000)}`;

const QUIZ_PROMPT = (tx) => `Generate exactly 10 multiple choice questions from the transcript below. English only.

YOUR ENTIRE RESPONSE MUST BE ONLY A JSON ARRAY. No intro text, no explanation, no markdown, no code blocks. Start your response with [ and end with ].

Format: [{"q":"Question?","options":["Option A","Option B","Option C","Option D"],"answer":0,"explanation":"Why this answer is correct"}]

Rules:
- answer is the 0-based index (0, 1, 2 or 3) of the correct option
- Exactly 10 questions covering different parts of the transcript
- Mix of conceptual, factual and application questions
- Make distractors plausible but clearly wrong

Transcript:
${tx.slice(0, 3000)}`;

export {
    Tabs,
    extractVideoId,
    fetchTranscript,
    callClaude,
    parseQuiz,
    downloadTxt,
    downloadHtml,
    downloadQuiz,
    SUMMARY_PROMPT,
    NOTES_PROMPT,
    QUIZ_PROMPT
}